from db.load.common import DataSchema

REC_SITE_SCHEMA = DataSchema(
    schema_map={
        "UFI": "unique_key",
        "VERS_DATE": "version_date",
        "NAME": "name",
        "LATITUDE": "latitude",
        "LONGITUDE": "longitude",
        "DIS_ACCESS": "disabled_access",
        "ACCESS_DSC": "access_descr",
        "FEE": "fee",
        "COMMENTS": "comments",
        "MAINTAINED_BY": "maintained_by",
        "CLOS_STAT": "closed_status",
        "CLOS_DESC": "closed_descr",
        "CLOS_START": "closed_on",
        "CLOS_OPEN": "reopen_on",
        "CLOS_REAS": "closed_reason",
        "CAMPING": "camping",
        "CAMPING_C": "camping_descr",
        "CAMPERVANNING": "campervanning",
        "CAMPERVAN_C": "campervanning_descr",
        "CAMPERVAN_TYPE": "campervan_type",
        "TB_VISITOR": "trail_bike_area",
        "TBVA_C": "trail_bike_area_descr",
        "HERITAGE": "heritage",
        "HERITAGE_C": "heritage_descr",
        "FISHING": "fishing",
        "FISHING_C": "fishing_descr",
        "FOSSICKING": "fossicking",
        "FOSSICK_C": "fossicking_descr",
        "HANG_GLIDE": "hang_gliding",
        "HANG_GLD_C": "hang_gliding_descr",
        "HORSE_RIDE": "horse_riding",
        "HORSERIDE_C": "horse_riding_descr",
        "PADDLING": "paddling",
        "PADDLING_C": "paddling_descr",
        "PICNICING": "picnicing",
        "PICNICING_C": "picnicing_descr",
        "REDUCE_NA": "noise_warning",
        "REDUCE_C": "noise_warning_descr",
        "ROCKCLIMB": "rock_climbing",
        "ROCKCLIMB_C": "rock_climbing_descr",
        "WALKINGDOG": "dog_walking",
        "WALKDOG_C": "dog_walking_descr",
        "WILDLIFE": "wildlife",
        "WILDLIFE_C": "wildlife_descr",
        "BBQ_ELEC": "num_bbq_electric",
        "BBQ_PIT": "num_bbq_pit",
        "BBQ_GAS": "num_bbq_gas",
        "BBQ_WOOD": "num_bbq_wood",
    },
    descr_attributes={
        "ACCESS_DSC",
        "COMMENTS",
        "CLOS_DESC",
        "CLOS_REAS",
        "CAMPING_C",
        "CAMPERVAN_C",
        "TBVA_C",
        "HERITAGE_C",
        "FISHING_C",
        "FOSSICK_C",
        "HANG_GLD_C",
        "HORSERIDE_C",
        "PADDLING_C",
        "PICNICING_C",
        "REDUCE_C",
        "ROCKCLIMB_C",
        "WALKDOG_C",
        "WILDLIFE_C",
    },
    uppercase_attributes={
        "DIS_ACCESS",
        "CLOS_STAT",
        "CLOS_REAS",
        "CAMPERVAN_TYPE",
    },
)
