config:
  send_anonymous_usage_stats: false
  use_colors: true

lookout:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      user: dbt_user
      password: dbt_user
      port: 5432
      dbname: lookout
      schema: layers
      threads: 4
      keepalives_idle: 0 # system default
      connect_timeout: 30 # seconds
      role: dbt_user
      sslmode: disable
