name: "lookout"
version: "0.0.1"
config-version: 2

profile: "lookout"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  'dbt_date:time_zone': 'Australia/Melbourne'

models:
  lookout:
    staging:
      +materialized: view
    layers:
      +materialized: table
